config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'news#home'
  get 'search', :to => 'searchs#index', :as => :search
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController 
	def home
		@stories = HackerService.new.get_top_15
		if params['channel'] == "true"
      render json: {
              success: true,
              partial: render_to_string('news/_stories', layout: false
              )
            }
    end
	end
end

app/controllers/searchs_controller.rb
require "i18n"

class SearchsController < ApplicationController 
	def index
		@stories = HackerService.new.search I18n.transliterate(params[:search])
		@word = I18n.transliterate(params[:search])
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController 
	def show
		@story = HackerService.new.get_comments params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Hacker News
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta name="turbolinks-cache-control" content="no-cache"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  
  body
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/news/_stories.html.slim
- @stories.each_with_index do |story,i|
	.story-box
	  p.index="#{i+1}."
	  .text-box
	    =link_to story[:story]['url']
	      p.text=story[:story]['title']
	    p.info="#{time_ago_in_words(DateTime.strptime(story[:story]['time'].to_s,'%s')).remove("about","almost","over")} ago"
	    -if story[:comments] != 0
	      =link_to story_path(story[:story]["id"])
	        p.info="| #{story[:comments]} comments"
	    -else
	      p.info="| #{story[:comments]} comments"

app/views/news/home.html.slim
.news data-controller="news"
.news-box#news
  =render "stories"

app/views/searchs/index.html.slim
.search data-controller="search"
.word data-target=@word
.news-box
  - @stories.each_with_index do |story,i|
    .story-box
      p.index="#{i+1}."
      .text-box
        =link_to story[:url]
          p.text #{story[:title]} 
        p.info="#{time_ago_in_words(story[:time].to_datetime).remove("about","almost","over")} ago" 
        -if story[:comments] != 0
          =link_to story_path(story[:id])
            p.info="| #{story[:comments]} comments"
        -else
          p.info="| #{story[:comments]} comments"

app/views/shared/_footer.html.slim
.search-box-mobile
  i.icon-search#search
  =form_tag(search_path, :method => "get", id: "search-form") do
    = text_field_tag :search, params[:search], autocomplete: :off, id: "search"
    = submit_tag 'Search', class: "submit-button"

app/views/shared/_header.html.slim
.navbar
  .left
    =link_to "/" do
      =image_tag "logo.png"
    =link_to 'Hacker News'.upcase,"/", class: 'title'
    =link_to "submit", "https://news.ycombinator.com/submit"
  .right
    .search-box
      i.icon-search#search
      =form_tag(search_path, :method => "get", id: "search-form") do
        = text_field_tag :search, params[:search], autocomplete: :off, id: "search"
        = submit_tag 'Search', class: "submit-button"
    =link_to "login", "https://news.ycombinator.com/login?goto=news"

.navbar-mobile
  .left
    =link_to "/" do
      =image_tag "logo.png"
    =link_to 'Hacker News'.upcase,"/", class: 'title'
  .right
    =link_to "submit", "https://news.ycombinator.com/submit"
    =link_to "login", "https://news.ycombinator.com/login?goto=news"

app/views/stories/_text.html.erb
<p class="text"><%=comment['text']%></p>

app/views/stories/show.html.slim
.news-box
  =link_to @story[:story]['url']
    p.story=@story[:story]['title']
  - @story[:comments].each_with_index do |comment,i|
    .comment-box
      .text-box
      	 =render "text", comment: comment
         p.info="#{time_ago_in_words(DateTime.strptime(comment['time'].to_s,'%s')).remove("about","almost","over")} ago"